// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using future_academy.Contexts;

#nullable disable

namespace future_academy.Migrations
{
    [DbContext(typeof(UniversityContext))]
    partial class UniversityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("future_academy.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patronomic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("future_academy.Models.Answer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Questionid")
                        .HasColumnType("integer");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Questionid");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("future_academy.Models.Appeal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("future_academy.Models.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("teacher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("future_academy.Models.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("future_academy.Models.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Testid")
                        .HasColumnType("integer");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Testid");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("future_academy.Models.ServicesInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("graduatesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("openDoorsDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("programsCount")
                        .HasColumnType("integer");

                    b.Property<int>("teachersCount")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("ServicesInfo");
                });

            modelBuilder.Entity("future_academy.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Testid")
                        .HasColumnType("integer");

                    b.Property<int?>("accountId")
                        .HasColumnType("integer");

                    b.Property<string>("department")
                        .HasColumnType("text");

                    b.Property<int?>("groupId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Testid");

                    b.HasIndex("accountId");

                    b.HasIndex("groupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("future_academy.Models.Test", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Courseid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Courseid");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("future_academy.Models.Answer", b =>
                {
                    b.HasOne("future_academy.Models.Question", null)
                        .WithMany("answers")
                        .HasForeignKey("Questionid");
                });

            modelBuilder.Entity("future_academy.Models.Question", b =>
                {
                    b.HasOne("future_academy.Models.Test", null)
                        .WithMany("questions")
                        .HasForeignKey("Testid");
                });

            modelBuilder.Entity("future_academy.Models.Student", b =>
                {
                    b.HasOne("future_academy.Models.Test", null)
                        .WithMany("passedStudents")
                        .HasForeignKey("Testid");

                    b.HasOne("future_academy.Models.Account", "account")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("future_academy.Models.Group", "group")
                        .WithMany()
                        .HasForeignKey("groupId");

                    b.Navigation("account");

                    b.Navigation("group");
                });

            modelBuilder.Entity("future_academy.Models.Test", b =>
                {
                    b.HasOne("future_academy.Models.Course", null)
                        .WithMany("tests")
                        .HasForeignKey("Courseid");
                });

            modelBuilder.Entity("future_academy.Models.Course", b =>
                {
                    b.Navigation("tests");
                });

            modelBuilder.Entity("future_academy.Models.Question", b =>
                {
                    b.Navigation("answers");
                });

            modelBuilder.Entity("future_academy.Models.Test", b =>
                {
                    b.Navigation("passedStudents");

                    b.Navigation("questions");
                });
#pragma warning restore 612, 618
        }
    }
}
